# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lorawan_server
from lorawan_server.models.api_data_rate import ApiDataRate  # noqa: E501
from lorawan_server.rest import ApiException


class TestApiDataRate(unittest.TestCase):
    """ApiDataRate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiDataRate(self):
        """Test ApiDataRate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lorawan_client.models.api_data_rate.ApiDataRate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
