# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lorawan_server
from lorawan_server.api.downlink_queue_api import DownlinkQueueApi  # noqa: E501
from lorawan_server.rest import ApiException


class TestDownlinkQueueApi(unittest.TestCase):
    """DownlinkQueueApi unit test stubs"""

    def setUp(self):
        self.api = lorawan_server.api.downlink_queue_api.DownlinkQueueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete(self):
        """Test case for delete

        Delete deletes an item from the queue.  # noqa: E501
        """
        pass

    def test_enqueue(self):
        """Test case for enqueue

        Enqueue adds the given item to the queue. When the node operates in Class-C mode, the data will be pushed directly to the network-server.  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        List lists the items in the queue for the given node.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
