# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lorawan_server
from lorawan_server.api.organization_api import OrganizationApi  # noqa: E501
from lorawan_server.rest import ApiException


class TestOrganizationApi(unittest.TestCase):
    """OrganizationApi unit test stubs"""

    def setUp(self):
        self.api = lorawan_server.api.organization_api.OrganizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user(self):
        """Test case for add_user

        Add a new user to an organization.  # noqa: E501
        """
        pass

    def test_create(self):
        """Test case for create

        Create a new organization.  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete an organization.  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete a user from an organization.  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        Get data for a particular organization.  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get data for a particular organization user.  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        Get organization list.  # noqa: E501
        """
        pass

    def test_list_users(self):
        """Test case for list_users

        Get organization's user list.  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update an existing organization.  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update a user in an organization.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
