# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lorawan_server
from lorawan_server.api.user_api import UserApi  # noqa: E501
from lorawan_server.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = lorawan_server.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        Create a new user.  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete a user.  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        Get data for a particular user.  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        Get user list.  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update an existing user.  # noqa: E501
        """
        pass

    def test_update_password(self):
        """Test case for update_password

        UpdatePassword updates a password.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
