# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lorawan_server
from lorawan_server.models.api_delete_extra_channel_response import ApiDeleteExtraChannelResponse  # noqa: E501
from lorawan_server.rest import ApiException


class TestApiDeleteExtraChannelResponse(unittest.TestCase):
    """ApiDeleteExtraChannelResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiDeleteExtraChannelResponse(self):
        """Test ApiDeleteExtraChannelResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_delete_extra_channel_response.ApiDeleteExtraChannelResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
