# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lorawan_server
from lorawan_server.api.node_api import NodeApi  # noqa: E501
from lorawan_server.rest import ApiException


class TestNodeApi(unittest.TestCase):
    """NodeApi unit test stubs"""

    def setUp(self):
        self.api = lorawan_server.api.node_api.NodeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate(self):
        """Test case for activate

        Activate (re)activates the node (only when ABP is set to true).  # noqa: E501
        """
        pass

    def test_create(self):
        """Test case for create

        Create creates the given node.  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete deletes the node matching the given DevEUI.  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        Get returns the node for the requested DevEUI.  # noqa: E501
        """
        pass

    def test_get_activation(self):
        """Test case for get_activation

        GetActivation returns the current activation details of the node (OTAA and ABP).  # noqa: E501
        """
        pass

    def test_get_frame_logs(self):
        """Test case for get_frame_logs

        GetFrameLogs returns the uplink / downlink frame log for the given DevEUI.  # noqa: E501
        """
        pass

    def test_get_random_dev_addr(self):
        """Test case for get_random_dev_addr

        GetRandomDevAddr returns a random DevAddr taking the NwkID prefix into account.  # noqa: E501
        """
        pass

    def test_list_by_application_id(self):
        """Test case for list_by_application_id

        ListByApplicationID lists the nodes by the given application ID, sorted by the name of the node.  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update updates the node matching the given DevEUI.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
