# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from lorawan_server.models.api_add_user_application import ApiAddUserApplication  # noqa: F401,E501
from lorawan_server.models.api_add_user_organization import ApiAddUserOrganization  # noqa: F401,E501


class ApiAddUserRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'applications': 'list[ApiAddUserApplication]',
        'is_active': 'bool',
        'is_admin': 'bool',
        'organizations': 'list[ApiAddUserOrganization]',
        'password': 'str',
        'session_ttl': 'int',
        'username': 'str'
    }

    attribute_map = {
        'applications': 'applications',
        'is_active': 'isActive',
        'is_admin': 'isAdmin',
        'organizations': 'organizations',
        'password': 'password',
        'session_ttl': 'sessionTTL',
        'username': 'username'
    }

    def __init__(self, applications=None, is_active=None, is_admin=None, organizations=None, password=None, session_ttl=None, username=None):  # noqa: E501
        """ApiAddUserRequest - a model defined in Swagger"""  # noqa: E501

        self._applications = None
        self._is_active = None
        self._is_admin = None
        self._organizations = None
        self._password = None
        self._session_ttl = None
        self._username = None
        self.discriminator = None

        if applications is not None:
            self.applications = applications
        if is_active is not None:
            self.is_active = is_active
        if is_admin is not None:
            self.is_admin = is_admin
        if organizations is not None:
            self.organizations = organizations
        if password is not None:
            self.password = password
        if session_ttl is not None:
            self.session_ttl = session_ttl
        if username is not None:
            self.username = username

    @property
    def applications(self):
        """Gets the applications of this ApiAddUserRequest.  # noqa: E501

        Add the user to the following applications.  # noqa: E501

        :return: The applications of this ApiAddUserRequest.  # noqa: E501
        :rtype: list[ApiAddUserApplication]
        """
        return self._applications

    @applications.setter
    def applications(self, applications):
        """Sets the applications of this ApiAddUserRequest.

        Add the user to the following applications.  # noqa: E501

        :param applications: The applications of this ApiAddUserRequest.  # noqa: E501
        :type: list[ApiAddUserApplication]
        """

        self._applications = applications

    @property
    def is_active(self):
        """Gets the is_active of this ApiAddUserRequest.  # noqa: E501

        If the user is active.  # noqa: E501

        :return: The is_active of this ApiAddUserRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this ApiAddUserRequest.

        If the user is active.  # noqa: E501

        :param is_active: The is_active of this ApiAddUserRequest.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def is_admin(self):
        """Gets the is_admin of this ApiAddUserRequest.  # noqa: E501

        If the user is a system-wide admin.  # noqa: E501

        :return: The is_admin of this ApiAddUserRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin):
        """Sets the is_admin of this ApiAddUserRequest.

        If the user is a system-wide admin.  # noqa: E501

        :param is_admin: The is_admin of this ApiAddUserRequest.  # noqa: E501
        :type: bool
        """

        self._is_admin = is_admin

    @property
    def organizations(self):
        """Gets the organizations of this ApiAddUserRequest.  # noqa: E501

        Add the user to the following organizations.  # noqa: E501

        :return: The organizations of this ApiAddUserRequest.  # noqa: E501
        :rtype: list[ApiAddUserOrganization]
        """
        return self._organizations

    @organizations.setter
    def organizations(self, organizations):
        """Sets the organizations of this ApiAddUserRequest.

        Add the user to the following organizations.  # noqa: E501

        :param organizations: The organizations of this ApiAddUserRequest.  # noqa: E501
        :type: list[ApiAddUserOrganization]
        """

        self._organizations = organizations

    @property
    def password(self):
        """Gets the password of this ApiAddUserRequest.  # noqa: E501

        Passowrd of the user.  # noqa: E501

        :return: The password of this ApiAddUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ApiAddUserRequest.

        Passowrd of the user.  # noqa: E501

        :param password: The password of this ApiAddUserRequest.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def session_ttl(self):
        """Gets the session_ttl of this ApiAddUserRequest.  # noqa: E501

        The session timeout, in minutes.  # noqa: E501

        :return: The session_ttl of this ApiAddUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._session_ttl

    @session_ttl.setter
    def session_ttl(self, session_ttl):
        """Sets the session_ttl of this ApiAddUserRequest.

        The session timeout, in minutes.  # noqa: E501

        :param session_ttl: The session_ttl of this ApiAddUserRequest.  # noqa: E501
        :type: int
        """

        self._session_ttl = session_ttl

    @property
    def username(self):
        """Gets the username of this ApiAddUserRequest.  # noqa: E501

        Username of the user.  # noqa: E501

        :return: The username of this ApiAddUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ApiAddUserRequest.

        Username of the user.  # noqa: E501

        :param username: The username of this ApiAddUserRequest.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiAddUserRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiAddUserRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
