# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiProfileSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'disable_assign_existing_users': 'bool'
    }

    attribute_map = {
        'disable_assign_existing_users': 'disableAssignExistingUsers'
    }

    def __init__(self, disable_assign_existing_users=None):  # noqa: E501
        """ApiProfileSettings - a model defined in Swagger"""  # noqa: E501

        self._disable_assign_existing_users = None
        self.discriminator = None

        if disable_assign_existing_users is not None:
            self.disable_assign_existing_users = disable_assign_existing_users

    @property
    def disable_assign_existing_users(self):
        """Gets the disable_assign_existing_users of this ApiProfileSettings.  # noqa: E501

        Existing users in the system can not be assigned to organizations and application and can not be listed by non global admin users.  # noqa: E501

        :return: The disable_assign_existing_users of this ApiProfileSettings.  # noqa: E501
        :rtype: bool
        """
        return self._disable_assign_existing_users

    @disable_assign_existing_users.setter
    def disable_assign_existing_users(self, disable_assign_existing_users):
        """Sets the disable_assign_existing_users of this ApiProfileSettings.

        Existing users in the system can not be assigned to organizations and application and can not be listed by non global admin users.  # noqa: E501

        :param disable_assign_existing_users: The disable_assign_existing_users of this ApiProfileSettings.  # noqa: E501
        :type: bool
        """

        self._disable_assign_existing_users = disable_assign_existing_users

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiProfileSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiProfileSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
