# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from lorawan_server.models.api_modulation import ApiModulation  # noqa: F401,E501


class ApiGetExtraChannelResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bandwidth': 'int',
        'bit_rate': 'int',
        'channel_configuration_id': 'str',
        'created_at': 'str',
        'frequency': 'int',
        'id': 'str',
        'modulation': 'ApiModulation',
        'spread_factors': 'list[int]',
        'updated_at': 'str'
    }

    attribute_map = {
        'bandwidth': 'bandwidth',
        'bit_rate': 'bitRate',
        'channel_configuration_id': 'channelConfigurationID',
        'created_at': 'createdAt',
        'frequency': 'frequency',
        'id': 'id',
        'modulation': 'modulation',
        'spread_factors': 'spreadFactors',
        'updated_at': 'updatedAt'
    }

    def __init__(self, bandwidth=None, bit_rate=None, channel_configuration_id=None, created_at=None, frequency=None, id=None, modulation=None, spread_factors=None, updated_at=None):  # noqa: E501
        """ApiGetExtraChannelResponse - a model defined in Swagger"""  # noqa: E501

        self._bandwidth = None
        self._bit_rate = None
        self._channel_configuration_id = None
        self._created_at = None
        self._frequency = None
        self._id = None
        self._modulation = None
        self._spread_factors = None
        self._updated_at = None
        self.discriminator = None

        if bandwidth is not None:
            self.bandwidth = bandwidth
        if bit_rate is not None:
            self.bit_rate = bit_rate
        if channel_configuration_id is not None:
            self.channel_configuration_id = channel_configuration_id
        if created_at is not None:
            self.created_at = created_at
        if frequency is not None:
            self.frequency = frequency
        if id is not None:
            self.id = id
        if modulation is not None:
            self.modulation = modulation
        if spread_factors is not None:
            self.spread_factors = spread_factors
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def bandwidth(self):
        """Gets the bandwidth of this ApiGetExtraChannelResponse.  # noqa: E501

        Bandwidth.  # noqa: E501

        :return: The bandwidth of this ApiGetExtraChannelResponse.  # noqa: E501
        :rtype: int
        """
        return self._bandwidth

    @bandwidth.setter
    def bandwidth(self, bandwidth):
        """Sets the bandwidth of this ApiGetExtraChannelResponse.

        Bandwidth.  # noqa: E501

        :param bandwidth: The bandwidth of this ApiGetExtraChannelResponse.  # noqa: E501
        :type: int
        """

        self._bandwidth = bandwidth

    @property
    def bit_rate(self):
        """Gets the bit_rate of this ApiGetExtraChannelResponse.  # noqa: E501

        Bit rate (in case of FSK modulation).  # noqa: E501

        :return: The bit_rate of this ApiGetExtraChannelResponse.  # noqa: E501
        :rtype: int
        """
        return self._bit_rate

    @bit_rate.setter
    def bit_rate(self, bit_rate):
        """Sets the bit_rate of this ApiGetExtraChannelResponse.

        Bit rate (in case of FSK modulation).  # noqa: E501

        :param bit_rate: The bit_rate of this ApiGetExtraChannelResponse.  # noqa: E501
        :type: int
        """

        self._bit_rate = bit_rate

    @property
    def channel_configuration_id(self):
        """Gets the channel_configuration_id of this ApiGetExtraChannelResponse.  # noqa: E501

        ID of the channel-configuration.  # noqa: E501

        :return: The channel_configuration_id of this ApiGetExtraChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._channel_configuration_id

    @channel_configuration_id.setter
    def channel_configuration_id(self, channel_configuration_id):
        """Sets the channel_configuration_id of this ApiGetExtraChannelResponse.

        ID of the channel-configuration.  # noqa: E501

        :param channel_configuration_id: The channel_configuration_id of this ApiGetExtraChannelResponse.  # noqa: E501
        :type: str
        """

        self._channel_configuration_id = channel_configuration_id

    @property
    def created_at(self):
        """Gets the created_at of this ApiGetExtraChannelResponse.  # noqa: E501

        Created-at timestamp.  # noqa: E501

        :return: The created_at of this ApiGetExtraChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ApiGetExtraChannelResponse.

        Created-at timestamp.  # noqa: E501

        :param created_at: The created_at of this ApiGetExtraChannelResponse.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def frequency(self):
        """Gets the frequency of this ApiGetExtraChannelResponse.  # noqa: E501

        Frequency.  # noqa: E501

        :return: The frequency of this ApiGetExtraChannelResponse.  # noqa: E501
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this ApiGetExtraChannelResponse.

        Frequency.  # noqa: E501

        :param frequency: The frequency of this ApiGetExtraChannelResponse.  # noqa: E501
        :type: int
        """

        self._frequency = frequency

    @property
    def id(self):
        """Gets the id of this ApiGetExtraChannelResponse.  # noqa: E501

        ID of the extra channel.  # noqa: E501

        :return: The id of this ApiGetExtraChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiGetExtraChannelResponse.

        ID of the extra channel.  # noqa: E501

        :param id: The id of this ApiGetExtraChannelResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def modulation(self):
        """Gets the modulation of this ApiGetExtraChannelResponse.  # noqa: E501

        Modulation.  # noqa: E501

        :return: The modulation of this ApiGetExtraChannelResponse.  # noqa: E501
        :rtype: ApiModulation
        """
        return self._modulation

    @modulation.setter
    def modulation(self, modulation):
        """Sets the modulation of this ApiGetExtraChannelResponse.

        Modulation.  # noqa: E501

        :param modulation: The modulation of this ApiGetExtraChannelResponse.  # noqa: E501
        :type: ApiModulation
        """

        self._modulation = modulation

    @property
    def spread_factors(self):
        """Gets the spread_factors of this ApiGetExtraChannelResponse.  # noqa: E501

        Spread-factors (in case of LoRa modulation).  # noqa: E501

        :return: The spread_factors of this ApiGetExtraChannelResponse.  # noqa: E501
        :rtype: list[int]
        """
        return self._spread_factors

    @spread_factors.setter
    def spread_factors(self, spread_factors):
        """Sets the spread_factors of this ApiGetExtraChannelResponse.

        Spread-factors (in case of LoRa modulation).  # noqa: E501

        :param spread_factors: The spread_factors of this ApiGetExtraChannelResponse.  # noqa: E501
        :type: list[int]
        """

        self._spread_factors = spread_factors

    @property
    def updated_at(self):
        """Gets the updated_at of this ApiGetExtraChannelResponse.  # noqa: E501

        Updated-at timestamp.  # noqa: E501

        :return: The updated_at of this ApiGetExtraChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ApiGetExtraChannelResponse.

        Updated-at timestamp.  # noqa: E501

        :param updated_at: The updated_at of this ApiGetExtraChannelResponse.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiGetExtraChannelResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiGetExtraChannelResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
