# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiAddUserOrganization(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_admin': 'bool',
        'organization_id': 'str'
    }

    attribute_map = {
        'is_admin': 'isAdmin',
        'organization_id': 'organizationID'
    }

    def __init__(self, is_admin=None, organization_id=None):  # noqa: E501
        """ApiAddUserOrganization - a model defined in Swagger"""  # noqa: E501

        self._is_admin = None
        self._organization_id = None
        self.discriminator = None

        if is_admin is not None:
            self.is_admin = is_admin
        if organization_id is not None:
            self.organization_id = organization_id

    @property
    def is_admin(self):
        """Gets the is_admin of this ApiAddUserOrganization.  # noqa: E501

        User has admin rights within the organization.  # noqa: E501

        :return: The is_admin of this ApiAddUserOrganization.  # noqa: E501
        :rtype: bool
        """
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin):
        """Sets the is_admin of this ApiAddUserOrganization.

        User has admin rights within the organization.  # noqa: E501

        :param is_admin: The is_admin of this ApiAddUserOrganization.  # noqa: E501
        :type: bool
        """

        self._is_admin = is_admin

    @property
    def organization_id(self):
        """Gets the organization_id of this ApiAddUserOrganization.  # noqa: E501

        ID of the organization.  # noqa: E501

        :return: The organization_id of this ApiAddUserOrganization.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this ApiAddUserOrganization.

        ID of the organization.  # noqa: E501

        :param organization_id: The organization_id of this ApiAddUserOrganization.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiAddUserOrganization, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiAddUserOrganization):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
