# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from lorawan_server.models.api_rx_info import ApiRXInfo  # noqa: F401,E501
from lorawan_server.models.api_tx_info import ApiTXInfo  # noqa: F401,E501


class ApiFrameLog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'str',
        'phy_payload_json': 'str',
        'rx_info_set': 'list[ApiRXInfo]',
        'tx_info': 'ApiTXInfo'
    }

    attribute_map = {
        'created_at': 'createdAt',
        'phy_payload_json': 'phyPayloadJSON',
        'rx_info_set': 'rxInfoSet',
        'tx_info': 'txInfo'
    }

    def __init__(self, created_at=None, phy_payload_json=None, rx_info_set=None, tx_info=None):  # noqa: E501
        """ApiFrameLog - a model defined in Swagger"""  # noqa: E501

        self._created_at = None
        self._phy_payload_json = None
        self._rx_info_set = None
        self._tx_info = None
        self.discriminator = None

        if created_at is not None:
            self.created_at = created_at
        if phy_payload_json is not None:
            self.phy_payload_json = phy_payload_json
        if rx_info_set is not None:
            self.rx_info_set = rx_info_set
        if tx_info is not None:
            self.tx_info = tx_info

    @property
    def created_at(self):
        """Gets the created_at of this ApiFrameLog.  # noqa: E501

        Timestamp of when the frame was logged.  # noqa: E501

        :return: The created_at of this ApiFrameLog.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ApiFrameLog.

        Timestamp of when the frame was logged.  # noqa: E501

        :param created_at: The created_at of this ApiFrameLog.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def phy_payload_json(self):
        """Gets the phy_payload_json of this ApiFrameLog.  # noqa: E501

        LoRaWAN PHYPayload as a JSON string.  # noqa: E501

        :return: The phy_payload_json of this ApiFrameLog.  # noqa: E501
        :rtype: str
        """
        return self._phy_payload_json

    @phy_payload_json.setter
    def phy_payload_json(self, phy_payload_json):
        """Sets the phy_payload_json of this ApiFrameLog.

        LoRaWAN PHYPayload as a JSON string.  # noqa: E501

        :param phy_payload_json: The phy_payload_json of this ApiFrameLog.  # noqa: E501
        :type: str
        """

        self._phy_payload_json = phy_payload_json

    @property
    def rx_info_set(self):
        """Gets the rx_info_set of this ApiFrameLog.  # noqa: E501

        RX-info set (in case of an uplink).  # noqa: E501

        :return: The rx_info_set of this ApiFrameLog.  # noqa: E501
        :rtype: list[ApiRXInfo]
        """
        return self._rx_info_set

    @rx_info_set.setter
    def rx_info_set(self, rx_info_set):
        """Sets the rx_info_set of this ApiFrameLog.

        RX-info set (in case of an uplink).  # noqa: E501

        :param rx_info_set: The rx_info_set of this ApiFrameLog.  # noqa: E501
        :type: list[ApiRXInfo]
        """

        self._rx_info_set = rx_info_set

    @property
    def tx_info(self):
        """Gets the tx_info of this ApiFrameLog.  # noqa: E501

        TX-info (in case of a downlink).  # noqa: E501

        :return: The tx_info of this ApiFrameLog.  # noqa: E501
        :rtype: ApiTXInfo
        """
        return self._tx_info

    @tx_info.setter
    def tx_info(self, tx_info):
        """Sets the tx_info of this ApiFrameLog.

        TX-info (in case of a downlink).  # noqa: E501

        :param tx_info: The tx_info of this ApiFrameLog.  # noqa: E501
        :type: ApiTXInfo
        """

        self._tx_info = tx_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiFrameLog, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiFrameLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
