# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiUpdateUserRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'is_active': 'bool',
        'is_admin': 'bool',
        'session_ttl': 'int',
        'username': 'str'
    }

    attribute_map = {
        'id': 'id',
        'is_active': 'isActive',
        'is_admin': 'isAdmin',
        'session_ttl': 'sessionTTL',
        'username': 'username'
    }

    def __init__(self, id=None, is_active=None, is_admin=None, session_ttl=None, username=None):  # noqa: E501
        """ApiUpdateUserRequest - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._is_active = None
        self._is_admin = None
        self._session_ttl = None
        self._username = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if is_active is not None:
            self.is_active = is_active
        if is_admin is not None:
            self.is_admin = is_admin
        if session_ttl is not None:
            self.session_ttl = session_ttl
        if username is not None:
            self.username = username

    @property
    def id(self):
        """Gets the id of this ApiUpdateUserRequest.  # noqa: E501

        The ID of the user to be updated.  # noqa: E501

        :return: The id of this ApiUpdateUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiUpdateUserRequest.

        The ID of the user to be updated.  # noqa: E501

        :param id: The id of this ApiUpdateUserRequest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def is_active(self):
        """Gets the is_active of this ApiUpdateUserRequest.  # noqa: E501

        If the user is active.  # noqa: E501

        :return: The is_active of this ApiUpdateUserRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this ApiUpdateUserRequest.

        If the user is active.  # noqa: E501

        :param is_active: The is_active of this ApiUpdateUserRequest.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def is_admin(self):
        """Gets the is_admin of this ApiUpdateUserRequest.  # noqa: E501

        If the user is a system-wide admin.  # noqa: E501

        :return: The is_admin of this ApiUpdateUserRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin):
        """Sets the is_admin of this ApiUpdateUserRequest.

        If the user is a system-wide admin.  # noqa: E501

        :param is_admin: The is_admin of this ApiUpdateUserRequest.  # noqa: E501
        :type: bool
        """

        self._is_admin = is_admin

    @property
    def session_ttl(self):
        """Gets the session_ttl of this ApiUpdateUserRequest.  # noqa: E501

        The session timeout, in minutes.  # noqa: E501

        :return: The session_ttl of this ApiUpdateUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._session_ttl

    @session_ttl.setter
    def session_ttl(self, session_ttl):
        """Sets the session_ttl of this ApiUpdateUserRequest.

        The session timeout, in minutes.  # noqa: E501

        :param session_ttl: The session_ttl of this ApiUpdateUserRequest.  # noqa: E501
        :type: int
        """

        self._session_ttl = session_ttl

    @property
    def username(self):
        """Gets the username of this ApiUpdateUserRequest.  # noqa: E501

        The new username.  # noqa: E501

        :return: The username of this ApiUpdateUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ApiUpdateUserRequest.

        The new username.  # noqa: E501

        :param username: The username of this ApiUpdateUserRequest.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiUpdateUserRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiUpdateUserRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
