# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from lorawan_server.models.api_data_rate import ApiDataRate  # noqa: F401,E501


class ApiRXInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel': 'int',
        'code_rate': 'str',
        'data_rate': 'ApiDataRate',
        'frequency': 'str',
        'lo_ra_snr': 'float',
        'mac': 'str',
        'rssi': 'int',
        'time': 'str',
        'timestamp': 'int'
    }

    attribute_map = {
        'channel': 'channel',
        'code_rate': 'codeRate',
        'data_rate': 'dataRate',
        'frequency': 'frequency',
        'lo_ra_snr': 'loRaSNR',
        'mac': 'mac',
        'rssi': 'rssi',
        'time': 'time',
        'timestamp': 'timestamp'
    }

    def __init__(self, channel=None, code_rate=None, data_rate=None, frequency=None, lo_ra_snr=None, mac=None, rssi=None, time=None, timestamp=None):  # noqa: E501
        """ApiRXInfo - a model defined in Swagger"""  # noqa: E501

        self._channel = None
        self._code_rate = None
        self._data_rate = None
        self._frequency = None
        self._lo_ra_snr = None
        self._mac = None
        self._rssi = None
        self._time = None
        self._timestamp = None
        self.discriminator = None

        if channel is not None:
            self.channel = channel
        if code_rate is not None:
            self.code_rate = code_rate
        if data_rate is not None:
            self.data_rate = data_rate
        if frequency is not None:
            self.frequency = frequency
        if lo_ra_snr is not None:
            self.lo_ra_snr = lo_ra_snr
        if mac is not None:
            self.mac = mac
        if rssi is not None:
            self.rssi = rssi
        if time is not None:
            self.time = time
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def channel(self):
        """Gets the channel of this ApiRXInfo.  # noqa: E501

        Channel number on which the frame was received.  # noqa: E501

        :return: The channel of this ApiRXInfo.  # noqa: E501
        :rtype: int
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this ApiRXInfo.

        Channel number on which the frame was received.  # noqa: E501

        :param channel: The channel of this ApiRXInfo.  # noqa: E501
        :type: int
        """

        self._channel = channel

    @property
    def code_rate(self):
        """Gets the code_rate of this ApiRXInfo.  # noqa: E501

        Code-rate.  # noqa: E501

        :return: The code_rate of this ApiRXInfo.  # noqa: E501
        :rtype: str
        """
        return self._code_rate

    @code_rate.setter
    def code_rate(self, code_rate):
        """Sets the code_rate of this ApiRXInfo.

        Code-rate.  # noqa: E501

        :param code_rate: The code_rate of this ApiRXInfo.  # noqa: E501
        :type: str
        """

        self._code_rate = code_rate

    @property
    def data_rate(self):
        """Gets the data_rate of this ApiRXInfo.  # noqa: E501

        Data-rate.  # noqa: E501

        :return: The data_rate of this ApiRXInfo.  # noqa: E501
        :rtype: ApiDataRate
        """
        return self._data_rate

    @data_rate.setter
    def data_rate(self, data_rate):
        """Sets the data_rate of this ApiRXInfo.

        Data-rate.  # noqa: E501

        :param data_rate: The data_rate of this ApiRXInfo.  # noqa: E501
        :type: ApiDataRate
        """

        self._data_rate = data_rate

    @property
    def frequency(self):
        """Gets the frequency of this ApiRXInfo.  # noqa: E501

        frequency.  # noqa: E501

        :return: The frequency of this ApiRXInfo.  # noqa: E501
        :rtype: str
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this ApiRXInfo.

        frequency.  # noqa: E501

        :param frequency: The frequency of this ApiRXInfo.  # noqa: E501
        :type: str
        """

        self._frequency = frequency

    @property
    def lo_ra_snr(self):
        """Gets the lo_ra_snr of this ApiRXInfo.  # noqa: E501

        LoRa SNR.  # noqa: E501

        :return: The lo_ra_snr of this ApiRXInfo.  # noqa: E501
        :rtype: float
        """
        return self._lo_ra_snr

    @lo_ra_snr.setter
    def lo_ra_snr(self, lo_ra_snr):
        """Sets the lo_ra_snr of this ApiRXInfo.

        LoRa SNR.  # noqa: E501

        :param lo_ra_snr: The lo_ra_snr of this ApiRXInfo.  # noqa: E501
        :type: float
        """

        self._lo_ra_snr = lo_ra_snr

    @property
    def mac(self):
        """Gets the mac of this ApiRXInfo.  # noqa: E501

        HEX encoded gateway MAC.  # noqa: E501

        :return: The mac of this ApiRXInfo.  # noqa: E501
        :rtype: str
        """
        return self._mac

    @mac.setter
    def mac(self, mac):
        """Sets the mac of this ApiRXInfo.

        HEX encoded gateway MAC.  # noqa: E501

        :param mac: The mac of this ApiRXInfo.  # noqa: E501
        :type: str
        """

        self._mac = mac

    @property
    def rssi(self):
        """Gets the rssi of this ApiRXInfo.  # noqa: E501

        RSSI / signal strength.  # noqa: E501

        :return: The rssi of this ApiRXInfo.  # noqa: E501
        :rtype: int
        """
        return self._rssi

    @rssi.setter
    def rssi(self, rssi):
        """Sets the rssi of this ApiRXInfo.

        RSSI / signal strength.  # noqa: E501

        :param rssi: The rssi of this ApiRXInfo.  # noqa: E501
        :type: int
        """

        self._rssi = rssi

    @property
    def time(self):
        """Gets the time of this ApiRXInfo.  # noqa: E501

        Time (when the gateway has a GPS).  # noqa: E501

        :return: The time of this ApiRXInfo.  # noqa: E501
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this ApiRXInfo.

        Time (when the gateway has a GPS).  # noqa: E501

        :param time: The time of this ApiRXInfo.  # noqa: E501
        :type: str
        """

        self._time = time

    @property
    def timestamp(self):
        """Gets the timestamp of this ApiRXInfo.  # noqa: E501

        Gateway internal timestamp.  # noqa: E501

        :return: The timestamp of this ApiRXInfo.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ApiRXInfo.

        Gateway internal timestamp.  # noqa: E501

        :param timestamp: The timestamp of this ApiRXInfo.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiRXInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiRXInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
