# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from lorawan_server.models.api_application_link import ApiApplicationLink  # noqa: F401,E501
from lorawan_server.models.api_get_user_response import ApiGetUserResponse  # noqa: F401,E501
from lorawan_server.models.api_organization_link import ApiOrganizationLink  # noqa: F401,E501
from lorawan_server.models.api_profile_settings import ApiProfileSettings  # noqa: F401,E501


class ApiProfileResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'applications': 'list[ApiApplicationLink]',
        'organizations': 'list[ApiOrganizationLink]',
        'settings': 'ApiProfileSettings',
        'user': 'ApiGetUserResponse'
    }

    attribute_map = {
        'applications': 'applications',
        'organizations': 'organizations',
        'settings': 'settings',
        'user': 'user'
    }

    def __init__(self, applications=None, organizations=None, settings=None, user=None):  # noqa: E501
        """ApiProfileResponse - a model defined in Swagger"""  # noqa: E501

        self._applications = None
        self._organizations = None
        self._settings = None
        self._user = None
        self.discriminator = None

        if applications is not None:
            self.applications = applications
        if organizations is not None:
            self.organizations = organizations
        if settings is not None:
            self.settings = settings
        if user is not None:
            self.user = user

    @property
    def applications(self):
        """Gets the applications of this ApiProfileResponse.  # noqa: E501


        :return: The applications of this ApiProfileResponse.  # noqa: E501
        :rtype: list[ApiApplicationLink]
        """
        return self._applications

    @applications.setter
    def applications(self, applications):
        """Sets the applications of this ApiProfileResponse.


        :param applications: The applications of this ApiProfileResponse.  # noqa: E501
        :type: list[ApiApplicationLink]
        """

        self._applications = applications

    @property
    def organizations(self):
        """Gets the organizations of this ApiProfileResponse.  # noqa: E501


        :return: The organizations of this ApiProfileResponse.  # noqa: E501
        :rtype: list[ApiOrganizationLink]
        """
        return self._organizations

    @organizations.setter
    def organizations(self, organizations):
        """Sets the organizations of this ApiProfileResponse.


        :param organizations: The organizations of this ApiProfileResponse.  # noqa: E501
        :type: list[ApiOrganizationLink]
        """

        self._organizations = organizations

    @property
    def settings(self):
        """Gets the settings of this ApiProfileResponse.  # noqa: E501


        :return: The settings of this ApiProfileResponse.  # noqa: E501
        :rtype: ApiProfileSettings
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this ApiProfileResponse.


        :param settings: The settings of this ApiProfileResponse.  # noqa: E501
        :type: ApiProfileSettings
        """

        self._settings = settings

    @property
    def user(self):
        """Gets the user of this ApiProfileResponse.  # noqa: E501


        :return: The user of this ApiProfileResponse.  # noqa: E501
        :rtype: ApiGetUserResponse
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this ApiProfileResponse.


        :param user: The user of this ApiProfileResponse.  # noqa: E501
        :type: ApiGetUserResponse
        """

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiProfileResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiProfileResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
