# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiUpdateChannelConfigurationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channels': 'list[int]',
        'id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'channels': 'channels',
        'id': 'id',
        'name': 'name'
    }

    def __init__(self, channels=None, id=None, name=None):  # noqa: E501
        """ApiUpdateChannelConfigurationRequest - a model defined in Swagger"""  # noqa: E501

        self._channels = None
        self._id = None
        self._name = None
        self.discriminator = None

        if channels is not None:
            self.channels = channels
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name

    @property
    def channels(self):
        """Gets the channels of this ApiUpdateChannelConfigurationRequest.  # noqa: E501

        Channels active in this configuration. These channel indices must map to the channel numbers as specified in the LoRaWAN Regional Parameters.  # noqa: E501

        :return: The channels of this ApiUpdateChannelConfigurationRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._channels

    @channels.setter
    def channels(self, channels):
        """Sets the channels of this ApiUpdateChannelConfigurationRequest.

        Channels active in this configuration. These channel indices must map to the channel numbers as specified in the LoRaWAN Regional Parameters.  # noqa: E501

        :param channels: The channels of this ApiUpdateChannelConfigurationRequest.  # noqa: E501
        :type: list[int]
        """

        self._channels = channels

    @property
    def id(self):
        """Gets the id of this ApiUpdateChannelConfigurationRequest.  # noqa: E501

        ID of the channel-configuration.  # noqa: E501

        :return: The id of this ApiUpdateChannelConfigurationRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiUpdateChannelConfigurationRequest.

        ID of the channel-configuration.  # noqa: E501

        :param id: The id of this ApiUpdateChannelConfigurationRequest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ApiUpdateChannelConfigurationRequest.  # noqa: E501

        Name of the channel-configuration.  # noqa: E501

        :return: The name of this ApiUpdateChannelConfigurationRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiUpdateChannelConfigurationRequest.

        Name of the channel-configuration.  # noqa: E501

        :param name: The name of this ApiUpdateChannelConfigurationRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiUpdateChannelConfigurationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiUpdateChannelConfigurationRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
