# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from lorawan_server.models.api_integration_kind import ApiIntegrationKind  # noqa: F401,E501


class ApiListIntegrationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'kinds': 'list[ApiIntegrationKind]'
    }

    attribute_map = {
        'kinds': 'kinds'
    }

    def __init__(self, kinds=None):  # noqa: E501
        """ApiListIntegrationResponse - a model defined in Swagger"""  # noqa: E501

        self._kinds = None
        self.discriminator = None

        if kinds is not None:
            self.kinds = kinds

    @property
    def kinds(self):
        """Gets the kinds of this ApiListIntegrationResponse.  # noqa: E501

        The integration kinds associated with the application.  # noqa: E501

        :return: The kinds of this ApiListIntegrationResponse.  # noqa: E501
        :rtype: list[ApiIntegrationKind]
        """
        return self._kinds

    @kinds.setter
    def kinds(self, kinds):
        """Sets the kinds of this ApiListIntegrationResponse.

        The integration kinds associated with the application.  # noqa: E501

        :param kinds: The kinds of this ApiListIntegrationResponse.  # noqa: E501
        :type: list[ApiIntegrationKind]
        """

        self._kinds = kinds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiListIntegrationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiListIntegrationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
