# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiGetChannelConfigurationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channels': 'list[int]',
        'created_at': 'str',
        'id': 'str',
        'name': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'channels': 'channels',
        'created_at': 'createdAt',
        'id': 'id',
        'name': 'name',
        'updated_at': 'updatedAt'
    }

    def __init__(self, channels=None, created_at=None, id=None, name=None, updated_at=None):  # noqa: E501
        """ApiGetChannelConfigurationResponse - a model defined in Swagger"""  # noqa: E501

        self._channels = None
        self._created_at = None
        self._id = None
        self._name = None
        self._updated_at = None
        self.discriminator = None

        if channels is not None:
            self.channels = channels
        if created_at is not None:
            self.created_at = created_at
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def channels(self):
        """Gets the channels of this ApiGetChannelConfigurationResponse.  # noqa: E501

        Channels active in this configuration. These channel indices must map to the channel numbers as specified in the LoRaWAN Regional Parameters.  # noqa: E501

        :return: The channels of this ApiGetChannelConfigurationResponse.  # noqa: E501
        :rtype: list[int]
        """
        return self._channels

    @channels.setter
    def channels(self, channels):
        """Sets the channels of this ApiGetChannelConfigurationResponse.

        Channels active in this configuration. These channel indices must map to the channel numbers as specified in the LoRaWAN Regional Parameters.  # noqa: E501

        :param channels: The channels of this ApiGetChannelConfigurationResponse.  # noqa: E501
        :type: list[int]
        """

        self._channels = channels

    @property
    def created_at(self):
        """Gets the created_at of this ApiGetChannelConfigurationResponse.  # noqa: E501

        The timestamp when the channel-configuration was created.  # noqa: E501

        :return: The created_at of this ApiGetChannelConfigurationResponse.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ApiGetChannelConfigurationResponse.

        The timestamp when the channel-configuration was created.  # noqa: E501

        :param created_at: The created_at of this ApiGetChannelConfigurationResponse.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def id(self):
        """Gets the id of this ApiGetChannelConfigurationResponse.  # noqa: E501

        ID of the channel-configuration.  # noqa: E501

        :return: The id of this ApiGetChannelConfigurationResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiGetChannelConfigurationResponse.

        ID of the channel-configuration.  # noqa: E501

        :param id: The id of this ApiGetChannelConfigurationResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ApiGetChannelConfigurationResponse.  # noqa: E501

        Name of the channel-configuration.  # noqa: E501

        :return: The name of this ApiGetChannelConfigurationResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiGetChannelConfigurationResponse.

        Name of the channel-configuration.  # noqa: E501

        :param name: The name of this ApiGetChannelConfigurationResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def updated_at(self):
        """Gets the updated_at of this ApiGetChannelConfigurationResponse.  # noqa: E501

        The timestamp when the channel-configuration was last updated.  # noqa: E501

        :return: The updated_at of this ApiGetChannelConfigurationResponse.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ApiGetChannelConfigurationResponse.

        The timestamp when the channel-configuration was last updated.  # noqa: E501

        :param updated_at: The updated_at of this ApiGetChannelConfigurationResponse.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiGetChannelConfigurationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiGetChannelConfigurationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
